### ISSUE TITLE
Please replace "myprefix" :)

### ISSUE THREAD

**Issue by jtsternberg** [salcode/genesis-webinar-cpt-cmb2#2]
In this guy: https://github.com/salcode/genesis-webinar-cpt-cmb2/blob/master/lib/genesis-cpt-archive-metabox.php

Per https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/README.md
(i know you know this)

**Comment by salcode** [comment]
Thanks for the reminder.

This is now updated 👍
